### ISSUE TITLE
Issue with running code. Error message "ValueError: Cannot set tensor: Dimension mismatch." is generated for any action

### ISSUE THREAD

**Issue by robisen1** [karanjakhar/yolov5-export-to-raspberry-pi#10]
Hi,

I am trying to get the code running. I have followed the installation instructions yet when I get run the code I get ValueError which usually means a issue with input data but I cannot see any issue in the code. Its looks pretty clean and I don't see what's actually happening. Has anyone see a error like this from "yolov5_tflite_inference.py" ? Any help appreciated. 

`pi@raspberrypi:~/yolov5-export-to-raspberry-pi $ python3 yolov5_tflite_folder_of_images_inference.py -w yolov5s-fp16.tflite -f images/
Namespace(weights='yolov5s-fp16.tflite', folder_path='images/', img_size=416, conf_thres=0.25, iou_thres=0.45)
Processing  images/bus.jpg  now ...
Traceback (most recent call last):
  File "/home/pi/yolov5-export-to-raspberry-pi/yolov5_tflite_folder_of_images_inference.py", line 28, in <module>
    detect_from_folder_of_images(opt.weights,opt.folder_path,opt.img_size,opt.conf_thres,opt.iou_thres)
  File "/home/pi/yolov5-export-to-raspberry-pi/yolov5_tflite_folder_of_images_inference.py", line 12, in detect_from_folder_of_images
    detect_image(weights,file,img_size,conf_thres,iou_thres)
  File "/home/pi/yolov5-export-to-raspberry-pi/yolov5_tflite_image_inference.py", line 34, in detect_image
    result_boxes, result_scores, result_class_names = yolov5_tflite_obj.detect(normalized_image_array)
  File "/home/pi/yolov5-export-to-raspberry-pi/yolov5_tflite_inference.py", line 136, in detect
    self.interpreter.set_tensor(self.input_details[0]['index'], input_data)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 572, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 416 but expected 448 for dimension 1 of input 0.
`

**Comment by karanjakhar** [comment]
It is due to difference in image input size.

**Comment by robisen1** [comment]
Yes I said that in the first sentence but I'm not sure why that would be
when I have not changed anything. Any thoughts one why if I just followed
the directions I would have the issue? Thanks for your rapid response. It
is appreciated.

**Comment by karanjakhar** [comment]
You have to change model input size. You are using default one I think.

**Comment by robisen1** [comment]
Thanks for your response. I am using the default. I will edit the code.
