### ISSUE TITLE
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model) NameError: name 'keras_model' is not defined

### ISSUE THREAD

**Issue by dhunjoshi** [karanjakhar/yolov5-export-to-raspberry-pi#2]
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
NameError: name 'keras_model' is not defined

**Comment by karanjakhar** [comment]
Please check that the configuration YAML file and model file are correct and retry. And if still this error then please let me know how to reproduce this error. If possible share your model and YAML file.
