### ISSUE TITLE
webcam couldn't open

### ISSUE THREAD

**Issue by singgihbekti** [karanjakhar/yolov5-export-to-raspberry-pi#8]
I pass all of the steps mentioned but the webcam doesn't show anything. In the folder, it has a video which cannot be opened. 
when I run this command
```
pi@raspberrypi:~/yolov5-export-to-raspberry-pi-main $ python3 yolov5_tflite_webcam_inference.py -w 5l_best-fp16.tflite
```

it shows only this
```
Namespace(weights='5l_best-fp16.tflite', webcam=0, img_size=416, conf_thres=0.25, iou_thres=0.45)
480 640
```

**Comment by qo6ep870405** [comment]
Same problem. I also changed the "yolov5s-fp16.tflite" to other weight, and it closed at the beginning. Have you solved it?

**Comment by karanjakhar** [comment]
It might be related to the model input size.

**Comment by karanjakhar** [comment]
If you can share the model weights I can reproduce the error.

**Comment by singgihbekti** [comment]
This one is .tflite file
https://drive.google.com/file/d/1bIq8ZkOZhG4w16Pnfkl6eVokBk4i5q1K/view?usp=sharing

and this is .pt file
https://drive.google.com/file/d/1FhmSvxWL4Ss83_4_DnMOcWweXJVz7K4Z/view?usp=sharing

**Comment by karanjakhar** [comment]
There was a minor problem with the code. Now it's working. I tested it with your model weights.

**Comment by dineshtardid** [comment]
@karanjakhar Can I use it for yolov8n, if not do you know any alternative method to convert yolov8 model.

**Comment by karanjakhar** [comment]
@dineshtardid I haven't tested it yet with Yolov8n. But I will test it and let you know.
